os: linux
matrix:
  include:
    - os: osx
    - dist: trusty
      sudo: required
  exclude:
    - os: linux

env:
- PYENV_PYTHON_VERSION=3.5.0

before_install:
- ci/travis/before_install.sh
install:
- ci/travis/build.sh